name: CI
on: [push]

jobs:
  run-tests:
    name: Run tests
    runs-on: macOS-latest
    env:
      BUNDLE_PATH: vendor/bundle
      MINT_PATH: vendor/mint
    steps:
      - uses: actions/checkout@master

      - name: Cache ${{ env.MINT_PATH }}
        uses: actions/cache@v1
        with:
          path: ${{ env.MINT_PATH }}
          key: ${{ runner.os }}-mint-${{ hashFiles('Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Cache ${{ env.BUNDLE_PATH }}
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Package/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Mint bootstrap
        run: |
          brew list mint > /dev/null || brew install mint
          mint bootstrap

      - name: Bundle install
        run: |
          gem install bundler -v `tail -1 Gemfile.lock`
          bundle config path ${{ env.BUNDLE_PATH }}
          bundle install --jobs 4 --retry 3

      - run: |
          mint run yonaskolb/XcodeGen xcodegen generate --project Package --spec Package/Package.yml
          set -o pipefail && xcodebuild -project Package/Package.xcodeproj -scheme App -sdk iphonesimulator clean build | bundle exec xcpretty
